import type { Metadata } from 'next';
import { K2D } from 'next/font/google';
import './globals.css';

// const inter = Inter({ subsets: ['latin'] });

const font = K2D({ subsets: ['latin'], weight: '400' });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang='en'
			suppressHydrationWarning
			className={font.className}>
			<body className='bg-gradient-to-b from-white to-gray-400 dark:bg-gradient-to-b dark:from-zinc-800 dark:to-zinc-950 min-h-screen'>{children}</body>
		</html>
	);
}
